apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: demo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore
  target:
    name: backend-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: backend-db
        property: username
    - secretKey: password
      remoteRef:
        key: backend-db
        property: password
